#!/bin/bash

# Name of the private key
private_key="school"

# Number of bits for the key
key_bits="4096"

# Passphrase
passphrase="betty"

# Generate RSA key pair
openssl genrsa -aes256 -passout pass:"$passphrase" -out "$private_key" "$key_bits"

# Provide feedback
echo "RSA key pair created successfully."
